// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package server

import (
	"context"

	"rpc-greet/internal/logic"
	"rpc-greet/internal/svc"
	"rpc-greet/transform"
)

type TransformServer struct {
	svcCtx *svc.ServiceContext
}

func NewTransformServer(svcCtx *svc.ServiceContext) *TransformServer {
	return &TransformServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformServer) Ping(ctx context.Context, in *transform.Request) (*transform.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
