// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

//go:generate mockgen -destination ./transform_mock.go -package transformclient -source $GOFILE

package transformclient

import (
	"context"

	"rpc-greet/transform"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request  = transform.Request
	Response = transform.Response

	Transform interface {
		Ping(ctx context.Context, in *Request) (*Response, error)
	}

	defaultTransform struct {
		cli zrpc.Client
	}
)

func NewTransform(cli zrpc.Client) Transform {
	return &defaultTransform{
		cli: cli,
	}
}

func (m *defaultTransform) Ping(ctx context.Context, in *Request) (*Response, error) {
	client := transform.NewTransformClient(m.cli.Conn())
	return client.Ping(ctx, in)
}
